# This is a build which gets triggered on every commit push, to
# ensure that we get some warnings when we push code that does
# not build on macOS.

name: macOS

on: [push]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4

#     - name: Exit if not on devel branch
#       if: github.ref != 'refs/heads/devel'
#       run: exit 1
      
#    - name: remove python 3.12
#      run:  brew uninstall python@3.12
          
    - name: get dependencies
      run:  brew install cmake ninja boost pcre gmp python@3.13 pkgconfig gtkmm3 adwaita-icon-theme catch2 tbb && python3 -m pip install --break-system-packages --user sympy gmpy2 numpy

    - name: configure
      run:  mkdir build && cd build && cmake -G Ninja -DENABLE_MATHEMATICA=OFF -DPython_EXECUTABLE=python3.12 ..
      
    - name: build
      run:  cd build && cmake --build .
      
    - name: test
      env:
        CTEST_OUTPUT_ON_FAILURE: 1
      run:  cd build && ctest ARGS="-V"
